### PR TITLE
✨ Add check if 2 cards are revealed on player cardgrid

### PR DESCRIPTION
**Pull request by fre-ben**
- Upon clicking a card a check will return a `true` if two cards are revealed
- If two cards are revealed, the player can't reveal any more cards

I'm not too sure right now about how I will implement the rounds and turns of each player, need to figure this out as it will be important for the next steps.

Next I'll have to add a check if all players in a game have revealed two cards.

Deployment: https://sisu-pipelin-revealcard-jdvmr4.herokuapp.com/
Fixes parts of #73

### CODE REVIEW

**Review by m-wiemers — APPROVED** [review]
gj 🚀

**Review by DNaunin — APPROVED** [review]
Great Job! 🚀

**Review by christophvogel — APPROVED** [review]
LGTM 👍

**Review by SilviaBarcellini — APPROVED** [review]
lgtm!! 👍

**Pull request merged**
